apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: staging
  source:
    repoURL: 'https://kiali.org/helm-charts'
    targetRevision: 1.58.0
    chart: kiali-operator
    helm:
      parameters:
        - name: cr.namespace
          value: istio-system
        - name: cr.create
          value: 'true'
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true