apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: staging
  source:
    path: applications/mlflow/overlays/local-minio-artifact-store
    repoURL: https://github.com/davidfox87/terraform-eks-acm-alb-istio.git
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
