apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: staging
  source:
    chart: istio/gateway
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.15.1
    helm:
      values: |
        gateways:
          istio-ingressgateway:
            type: NodePort
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true