apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-foxy-infra
  namespace: argocd
  labels:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: staging
  source:
    path: infra/crossplane/team-foxy
    repoURL: https://github.com/davidfox87/crossplane-eks-argocd-mlops.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true