apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: staging
  source:
    path: applications/argo-workflows/overlays/staging
    repoURL: https://github.com/davidfox87/terraform-eks-acm-alb-istio.git
    targetRevision: HEAD
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true