apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ray-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: helm-chart/ray-cluster
    repoURL: https://github.com/ray-project/kuberay.git
    targetRevision: ray-cluster-chart-latest
  destination:
    namespace: ray-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
